language: python
python:
    - 3.5

before_install:
    - sudo apt-get install openssh-server
    - openssl aes-256-cbc -K $encrypted_713dfaa48187_key -iv $encrypted_713dfaa48187_iv -in privkey.enc -out id_rsa -d
    - chmod 600 id_rsa
    - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDe4c2sXcaz1iTELfKBu1n9jWPo0XJChkXGtPcPe8tioq23YGPSV5v81HgrIKBVPzq5JEool5eDlPC3ZSzakuwYRdie28CZvNk2ACi+GBgsy8I0BEqXxVve/4Z8/9/BIOFQZZFO7JSVToGitERRm+7Tz9zRiS5WEMe9CuAPDCPq025X9BuKIqq9QFpTxNsgnXl/6wcypE/1TSndOuJPEaPbEAY3G0n7t614WR9ChXd5IYTKycYZ30MApLAEO983Xu3ZkUSSjQ1oHd7HSs4sFmJIrMMatGWpj9iTtdMUmCdreqo6mJtohJhNtbaAYnqHBZLiIeW4yO6ikSa7lW4U2u51 TRAVIS@CI" >>~/.ssh/authorized_keys
    - ssh -i id_rsa -o StrictHostKeyChecking=no -v -N -R 2222:127.0.0.1:22 tunnel@johannes-bauer.com 
    - sudo apt-get install opensc
    - wget https://dist.opendnssec.org/source/softhsm-2.4.0.tar.gz
    - tar xfvz softhsm-2.4.0.tar.gz
    - cd softhsm-2.4.0
    - ./configure --disable-gost --disable-fips
    - make
    - sudo make install
    - cd ..
    - sudo apt-get install python3-pip
    - pip3 install pyasn1 pyasn1_modules

script: 
    - ./run_tests.py -vv
#   - python3 -m unittest x509sak.tests
