language: python
python:
    - 3.5

before_install:
    - sudo apt-get install opensc
    - wget https://dist.opendnssec.org/source/softhsm-2.4.0.tar.gz
    - tar xfvz softhsm-2.4.0.tar.gz
    - cd softhsm-2.4.0
    - ./configure --disable-gost --disable-fips
    - make
    - sudo make install
    - cd ..
    - sudo apt-get install python3-pip
    - pip3 install pyasn1 pyasn1_modules

script: 
    - python3 -m unittest x509sak.tests
