language: python
python:
    - 3.5

before_install:
    - sudo apt-get install python3-pip graphviz
    - pip3 install pyasn1 pyasn1_modules

script: 
    - ./run_tests.py --exclude HardwareTokenTests
